title: Sean's 90s Website
description: Skate videos, cat pics, random thoughts, and more!
baseurl: ""
url: "https://seanysdf.github.io/seans-website"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

collections:
  skating:
    output: true
    permalink: /skating/:path/
  cats:
    output: true
    permalink: /cats/:path/
  journal:
    output: true
    permalink: /journal/:path/
  random:
    output: true
    permalink: /random/:path/

defaults:
  - scope:
      path: ""
      type: "skating"
    values:
      layout: "skating_post"
  - scope:
      path: ""
      type: "cats"
    values:
      layout: "cat_post"
  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal_post"
  - scope:
      path: ""
      type: "random"
    values:
      layout: "random_post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
```

## .github/workflows/jekyll-gh-pages.yml (GitHub Actions workflow)
```yaml
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: bundle install
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2